# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Form-Processor
version:      0.04
version_from: lib/Form/Processor.pm
installdirs:  site
requires:
    Rose::Object:                  0.015
    Scalar::Util:                  1.18
    Test::More:                    0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
